language: python
python: 3.7

install:
- pip install bikeshed
- bikeshed update

# TODO(csharrison): Add --die-on=warning once warnings are all fixed.
script:
- mkdir -p out
- bikeshed spec index.bs out/index.html

branches:
  only:
  - main

before_deploy:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d

deploy:
  provider: pages
  local_dir: out
  deploy_key: deploy_key
  on:
    branch: main
  edge: true

notifications:
  email:
    on_success: never
    on_failure: always
