name: Build
on:
  pull_request:
    branches:
    - main
    paths:
    - 'Makefile'
    - 'index.bs'
  push:
    branches:
    - main
    paths:
    - 'Makefile'
    - 'header-validator/validate-json.js'
    - 'index.bs'
    - 'validate-headers.html'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
