name: Flexible Event Lint

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflow/lint-flexible-event.yml'
      - '.prettierrc.json'
      - 'flexible-event/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflow/lint-flexible-event.yml'
      - '.prettierrc.json'
      - 'flexible-event/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
        working-directory: 'flexible-event'
      - run: npm run lint:check
        working-directory: 'flexible-event'
