name: Schema Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflow/test-schema.yml'
      - 'schema/*'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflow/test-schema.yml'
      - 'schema/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
        working-directory: 'schema'
      - run: npm run build --if-present
        working-directory: 'schema'
      - run: npm test
        working-directory: 'schema'
