name: Header Validator Tests

on:
  push:
    branches: [ main ]
    paths: [ 'header-validator' ]
  pull_request:
    branches: [ main ]
    paths: [ 'header-validator' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
        working-directory header-validator
      - run: npm run build --if-present
        working-directory header-validator
      - run: npm test
        working-directory header-validator
