name: Flexible Event Privacy Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflow/test-flexible-event.yml'
      - '.prettierrc.json'
      - 'flexible-event/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflow/test-flexible-event.yml'
      - '.prettierrc.json'
      - 'flexible-event/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'flexible-event'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint:check
