name: Flexible Event Privacy Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflow/test-flexible-event.yml'
      - 'flexible-event/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflow/test-flexible-event.yml'
      - 'flexible-event/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
        working-directory: 'flexible-event'
      - run: npm run build --if-present
        working-directory: 'flexible-event'
      - run: npm test
        working-directory: 'flexible-event'
